matrix:
  include:
  -	language: node_js
	node_js:
	  - "8.10.0"
	env:
	  - NODE_VERSION="
	before_install:
	  - nvm install $NODE_VERSION
	scrpt: nmp "test"
	#run the script

  - language: python
  	python: 2.7
	script:
	  - python script.py

notifications:
  email:
  	- kirubel.m.tadesse@gmail.com

